=== shaeongit/Trabajando_con_XML-_DTD_y_XSD/Ejercicio_01/Ejercicio_01.dtd
<!ELEMENT catalogo (libros, revistas, usuarios, prestamos)>
<!ATTLIST catalogo fecha CDATA #REQUIRED>

<!ELEMENT libros (libro*)>      
<!ELEMENT libro (titulo, anio, autores+, etiquetas*)>
<!ATTLIST libro id ID #REQUIRED>
<!ATTLIST libro categoria CDATA #REQUIRED>
<!ATTLIST libro isbn CDATA #REQUIRED>
<!ATTLIST libro paginas CDATA #IMPLIED>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ELEMENT autores (autor+)>
<!ELEMENT autor (nombre, orcid?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT orcid (#PCDATA)>
<!ELEMENT etiquetas (etiqueta*)>
<!ELEMENT etiqueta (#PCDATA)>

<!ELEMENT revistas (revista*)>
<!ELEMENT revista (titulo, anio)>
<!ATTLIST revista id ID #REQUIRED>
<!ATTLIST revista area CDATA #REQUIRED>
<!ATTLIST revista issn CDATA #REQUIRED>
<!ATTLIST revista numero CDATA #REQUIRED>

<!ELEMENT usuarios (usuario*)>
<!ELEMENT usuario (nombre, email)>
<!ATTLIST usuario id ID #REQUIRED>
<!ATTLIST usuario tipo CDATA #REQUIRED>
<!ELEMENT email (#PCDATA)>


<!ELEMENT prestamos (prestamo*)>
<!ELEMENT prestamo (fecha_inicio, fecha_fin?, estado)>
<!ATTLIST prestamo id ID #REQUIRED>
<!ATTLIST prestamo itemRef IDREF #REQUIRED>
<!ATTLIST prestamo usuarioRef IDREF #REQUIRED>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT fecha_fin (#PCDATA)>
<!ELEMENT estado (#PCDATA)>

=== shaeongit/Trabajando_con_XML-_DTD_y_XSD/Ejercicio_01/Ejercicio_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE catalogo SYSTEM "Ejercicio_01.dtd">-->

<catalogo fecha="2025-10-04" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Ejercicio_01.xsd">
    <libros>
        <libro id="L001"
               categoria="novela"
               isbn="9780306406157"
               paginas="352">
            <titulo>La sombra del viento</titulo>
            <anio>2001</anio>
            <autores>
                <autor>
                    <nombre>Carlos Ruiz Zafón</nombre>
                    <orcid>0000-0002-1825-0097</orcid>
                </autor>
            </autores>
            <etiquetas>
                <etiqueta>misterio</etiqueta>
                <etiqueta>barcelona</etiqueta>
            </etiquetas>
        </libro>
        <libro id="L002"
               categoria="tecnico"
               isbn="9780134685991">
            <titulo>Effective Java</titulo>
            <anio>2018</anio>
            <autores>
                <autor>
                    <nombre>Joshua Bloch</nombre>
                </autor>
            </autores>
        </libro>
    </libros>
    <revistas>
        <revista id="R100"
                 area="computacion"
                 issn="1234-567X"
                 numero="42">
            <titulo>Journal of Programming</titulo>
            <anio>2024</anio>
        </revista>
    </revistas>
    <usuarios>
        <usuario id="U01"
                 tipo="alumno">
            <nombre>Raúl Albiol</nombre>
            <email>raul@example.edu</email>
        </usuario>
        <usuario id="U02"
                 tipo="profesor">
            <nombre>Marta Ibáñez</nombre>
            <email>marta.ibanez@uax.es</email>
        </usuario>
    </usuarios>
    <prestamos>
        <prestamo id="P0001"
                  itemRef="L001"
                  usuarioRef="U01">
            <fecha_inicio>2025-09-20</fecha_inicio>
            <fecha_fin>2025-10-05</fecha_fin>
            <estado>devuelto</estado>
        </prestamo>
        <prestamo id="P0002"
                  itemRef="R100"
                  usuarioRef="U02">
            <fecha_inicio>2025-09-28</fecha_inicio>
            <estado>en_curso</estado>
        </prestamo>
    </prestamos>
</catalogo>
